name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your interest in contributing to our project! We appreciate your dedication to improving our project. Before you create an issue, please take a moment to ensure that you provide as much relevant information as possible"
        pr-message: "Thank you for your commitment to improving our project by submitting a Pull Request (PR). We value your contribution and want to ensure a smooth and efficient review process."
